name: Tests on PR

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    uses: hasznaltauto/workflow-php/.github/workflows/lint.yml@v1
    with:
      php-versions: '["5.5.38", "5.6.40", "7.1.33"]'

  checkstyle:
    needs:
      - lint
    uses: hasznaltauto/workflow-php/.github/workflows/checkstyle.yml@v1
    secrets:
      GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.WORKFLOW_PAT }}

  unit-tests:
    needs:
      - lint
      - checkstyle
    uses: hasznaltauto/workflow-php/.github/workflows/phpunit.yml@v1
    with:
      php-versions: '["5.5.38", "5.6.40", "7.1.33"]'
